# Generated by Django 4.2.1 on 2023-07-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_authorprofile'),
        ('blog', '0004_alter_comment_created_at_alter_comment_object_id'),
    ]

    operations = [
    ]
